import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#ffdbcc",
        "on-surface-variant": "#414755",
        secondary: "#545f73",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#586377",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#c64f00",
        "on-tertiary-fixed": "#351000",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#7c2e00",
        outline: "#717786",
        "on-primary-fixed": "#001a41",
        "primary-fixed": "#d8e2ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "inverse-primary": "#adc6ff",
        "primary-container": "#0070eb",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        primary: "#0058bc",
        tertiary: "#9e3d00",
        "outline-variant": "#c1c6d7",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#005bc1",
        background: "#f7f9fb",
        "secondary-container": "#d5e0f8",
        "tertiary-fixed-dim": "#ffb595",
        error: "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        surface: "#f7f9fb",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed-variant": "#004493",
        "on-primary-container": "#fefcff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
      },
      spacing: {
        "margin-desktop": "32px",
        "panel-padding": "24px",
        unit: "4px",
        gutter: "16px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "mono-label": ["var(--font-space-mono)", "Space Mono", "monospace"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "mono-label": ["13px", { lineHeight: "16px" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
